name: Run Code Quality Check

permissions:
  contents: write
  
on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main
  workflow_dispatch:

jobs:
  test:
    name: "Code Quality Check"
    env:
      PYTHONPATH: .
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
          cache: 'pip' # caching pip dependencies

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pre-commit
          
      - name: Run pre-commit hooks
        run: |
          # Pre-commit exits with code 1 when it makes changes. We don't want
          # the workflow to fail in that case, so ignore the exit code.
          pre-commit run --all-files || true

      - name: Commit and push changes
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: apply pre-commit fixes"
            BRANCH="${GITHUB_HEAD_REF:-${GITHUB_REF_NAME}}"
            git push origin "HEAD:${BRANCH}"
          fi
